### ISSUE TITLE
Consolidate and Refine Work Items and Describe Higher-Level Goals

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-charter-drafts#24]
- Discovery (5) -> one Discovery Improvements
- All Protocol Bindings, Payload Bindings into one work items; "Work on new protocol bindings as appropriate"

**Comment by mmccool** [comment]
Note that PR #31 only partially addresses this issue, so it hasn't been marked as "resolving" this issue.

**Comment by mmccool** [comment]
Additional work to do:
- Merge Linting and Validation work items
- Merge Canonicalization and signing
- (Perhaps) Merge Payload and Protocol Bindings, mention "in support of ecosystem standards"?  Perhaps defer details...
- Reorder so e.g. all TD items are together

Please consider during TD call and propose a PR.

**Comment by mmccool** [comment]
Instead of categories, maybe have a paragraph that lists work items that contribute to particular goals, e.g. Digital Twins.

**Comment by mmccool** [comment]
Comments from meeting:
- Still need to uplevel, some are still overly detailed, not appropriate for the audience
- Not enough to list topics, need to describe goals, motivations, etc.
- Maybe add a preface that work items are "Specific Technical goals"

**Comment by mmccool** [comment]
Still needs more refinement and consolidation.  Also needs a higher-level set of goals, e.g. "Support Digitial Twin functionality", but easier to put that in a paragraph rather than using hierarchical categories.

**Comment by egekorkan** [comment]
I have a proposal to reduce the current list to 3 items plus 2 that I could not reorganize.

- Support WoT _integration_: Binding Templates (mechanism, protocol and payloads), Security Organization, Profiles
- Increase descriptiveness of TDs: Manageable actions, timeseries, connection info and repeated payloads
- Improve management of TDs and TMs: Discovery updates, versioning, validation and linting, canonicalization and signing

The 2 that are now left out are Onboarding and Geolocation. 
- I think that Onboarding is a bit too open and we need further discussion on this. I feel it needs its own deliverable.
- Geolocation should be removed in my opinion since it is not clear what is really needed. I do not think that there is something **new** we have to _invent_ . See https://w3c.github.io/wot-thing-description/#semantic-annotations-example-geoloc 

I will create a PR to consolidate the first 3 but I will not remove geolocation at the moment.

**Comment by benfrancis** [comment]
I like what you're trying to do here.

> Support WoT integration: Binding Templates (mechanism, protocol and payloads), Security Organization, Profiles
... 
> The WG will improve the usability of WoT in other ecosystems and communities.

Is this really what profiles do? Binding Templates and Profiles are kind of two opposite approaches to _interoperability_. The former takes a descriptive approach to enable one-to-one integrations between brownfield technologies, and the latter takes a prescriptive approach to enable universal plug-and-play interoperability between greenfield WoT implementations. I don't think profiles really "integrate" as such. Would "**Support WoT Interoperability**" be a better heading?

> I think that Onboarding is a bit too open and we need further discussion on this. I feel it needs its own deliverable.

I agree that "onboarding" is still a bit ephemeral but I personally see it as part of Discovery, not a separate deliverable. This could come under the "Improve Management of TDs" heading.

> Geolocation should be removed in my opinion since it is not clear what is really needed.

I agree it's not clear what is needed. Perhaps just a recommendation of a particular geolocation ontology in Profile and Discovery, but that's been hard to agree on so far. You could argue this point comes under "Increase descriptiveness of TDs", but it may not relate to the Thing Description and Binding Template deliverables.

**Comment by egekorkan** [comment]
@benfrancis thanks for the comment. I agree with all your points except for two small details.

1. I think that onboarding is part of the discovery but it does not fit well under the "Management of TDs" section. It is still ok though but maybe a better naming can be used.
2. "Finally, does this PR remove too much detail? It's quite high level." -> I did not understand what you mean here.

**Comment by benfrancis** [comment]
> 2\. "Finally, does this PR remove too much detail? It's quite high level." -> I did not understand what you mean here.

I just meant that this PR removes a lot of text which describes details about the work that's planned. I'm not sure what level of detail is appropriate for a charter, but maybe it goes too far.
