### ISSUE TITLE
Organize Deliverables for Protocol Bindings

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-charter-drafts#26]
- Informative deliverables (Notes) for individual bindings
- Mention use of "hub" document as a registry

Owner: Ege

**Comment by egekorkan** [comment]
#31 fixes this to a degree. @mmccool is the intention here that I define 2 new work items with the bullet points above?

**Comment by mmccool** [comment]
@ege, no, I don't think these are work items, just need to mention the Notes under informative deliverables and perhaps edit the "normative" deliverable to refer them.  However, let's discuss in the call today.

**Comment by egekorkan** [comment]
My comment from Call of 15.02:
- We should not have REC for each binding, it means having too many requirements in the charter, raising issues in different levels
- We should have a REC for the core document.
- Each binding is a W3C WG Note but the Core Document (which is a REC), specifies additional requirements on top of the basic W3C requirements for publishing notes. These can include having at least two implementations or other requirements we put.

**Comment by sebastiankb** [comment]
in today's TD call, we did some discussion on the bindings for the next charter. Please find here the slides that I have presented. I like to share the slides in tomorrow's charter meeting as well: [WoT_Binding_2.0.pdf](https://github.com/w3c/wot-charter-drafts/files/10745556/WoT_Binding_2.0.pdf)

**Comment by benfrancis** [comment]
@sebastiankb wrote:
> Please find here the slides that I have presented. I like to share the slides in tomorrow's charter meeting as well: [WoT_Binding_2.0.pdf](https://github.com/w3c/wot-charter-drafts/files/10745556/WoT_Binding_2.0.pdf)

This is interesting, thank you for sharing. I was disappointed that this topic didn't get discussed on the call.

I agree in principle with the idea that the top level document for bindings should be a REC containing registry sections and that those registries could point to W3C Notes (to reduce publication overhead). However, I do wonder about the implications of the binding documents being non-normative Notes. As I understand it, W3C Group Notes are really intended for supporting documentation such as use cases and requirements, design principles and best practices - documents that are not intended to be a formal standard.

If the binding documents are going to contain implementable assertions essential for consuming Things and are going to be cited by other RECs, is that enough? Particularly if normative sections of the Thing Description specification like security mechanisms are moved to binding documents as proposed in the draft charter, and if Profiles reference binding documents instead of defining their own protocol bindings as proposed in https://github.com/w3c/wot-profile/issues/285#issuecomment-1433087304.

Regarding the naming, I have concerns about calling the documents "protocol bindings" rather than "protocol binding templates", which I have explained in detail in #14. For what it's worth, if the binding documents _are_ renamed from "binding template" to "binding" then I think the top level document should just be called "WoT Bindings" since its main purpose is to be a registry of bindings and define the criteria for being included in that registry, not just to provide a template.
