### ISSUE TITLE
TD and TM restructuring

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-charter-drafts#33]
- Should TD and TM be different documents?
- Alternatively, should we rename the document to something like "Thing Description and Model"?
- Should there be internal reorganization?
- How do we handle versions?
- If we change the name, will the short URL have to change?

**Comment by egekorkan** [comment]
We had an internal discussion on this and are more in favor of not splitting the documents. We will go into more detail in the TD meeting tomorrow but some initial comments:
- The concepts are tightly linked to each other
- The current length of the TD spec is actually not too much. If we look at the printed version, we have 138 pages. In comparison, JSON-LD 1.1 has 200+ and HTML5 has 900+ (not the best comparison)
- We can evaluate if another specification template is possible. In HTML5 there is a multipage version or specs built with tools like Antora (see [here](https://docs.antora.org/antora-ui-default/)) that allows navigating big specs.
- Regarding naming: We should definitely keep "Thing Description" together since it is like a brand. We can talk more about this.

The slides from @sebastiankb from 2 weeks ago are available at https://github.com/w3c/wot-charter-drafts/files/10745556/WoT_Binding_2.0.pdf

**Comment by mlagally** [comment]
Due to the history of the evolution of the TD spec, the "instance" definition was happening before the "class". 
I think the model should be a first class citizen, this will also simplify the definition of digital twins.
